<a href="https://colab.research.google.com/github/sseegg300/data/blob/main/2026%EA%B0%95%EC%84%9C_%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**사전 준비**

1.   코랩 기본사용법      

      *   폴더 만들기
       

2.   판다스 & 맷플롭립

#🌞판다스
*   파이썬 에서 사용하는 데이터 분석 라이브러리
 - 관용적으로 별칭 pd를 사용

In [ ]:
import pandas as pd

- 판다스 데이터 타입
  - Series : 1차원
  - DataFrame : 2차원(행, 열)

## 1️⃣Series
*  1차원 데이터(정수,실수,문자열등)
*  Series객체 생성
    *   (예) 1월 부터 5월까지 평균데이터(-10,-5,10,15,20)

In [ ]:
#Series객체 생성(1)                                   #Ctrl + . :funtion list help
temp = pd.Series([1.2,3.5,5.8,13.3,15.7])
temp
#type(temp)

0     1.2
1     3.5
2     5.8
3    13.3
4    15.7
dtype: float64

In [ ]:
#3월 온도 알아보기
#temp[2]   #np.int64(10) :값의 타입이 NumPy에서 정의한 64비트 정수형이기 때문
print(temp[2])

5.8

/tmp/ipykernel_1883/1907096423.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(temp[2])

In [ ]:
#Series객체 생성(2)
data = [1.2,3.5,5.8,13.3,15.7]
idx = ['1월', '2월', '3월', '4월','5월']
temp = pd.Series(data,
              index = idx)
temp
#type(s)

1월     1.2
2월     3.5
3월     5.8
4월    13.3
5월    15.7
dtype: float64

In [ ]:
print(temp['3월']) #3월 데이터 출력
#print(temp['6월']) #존재하지 않는 인덱스 - error

5.8

## 2️⃣DataFrame
*  2차원 데이터
*  Series객체들의 모음

### DF 생성(1) <- 리스트 구조

In [ ]:
#DataFrame 생성(1)  DF 생성(1) <- 리스트 구조
data = [[15, 160.5, '서울'],
        [16, 158.3, '대전'],
        [20, 175.0, '대구'],
        [19, 178.4, '부산'],
        [23, 185.0, '제주']]

idx = ['홍길동', '이순신', '유관순', '박지훈', '박정민']

cols = ['나이', '키', '사는곳']

df = pd.DataFrame(data,
             index = idx,
             columns=cols)
df

     나이      키 사는곳
홍길동  15  160.5  서울
이순신  16  158.3  대전
유관순  20  175.0  대구
박지훈  19  178.4  부산
박정민  23  185.0  제주

In [ ]:
type(df)

In [ ]:
df['나이']  #df[컬럼명] - Series타입이라 df[]안에 컬럼명을 str로 바로 입력가능
type(df['나이'])

In [ ]:
df[['나이','키']]  #df[[컬럼명2,컬럼명2]] - DataFrame타입이라 df[]안에 컬럼명을 리스트형식으로 입력
#type(df[['나이','키']])

     나이      키
홍길동  15  160.5
이순신  16  158.3
유관순  20  175.0
박지훈  19  178.4
박정민  23  185.0

In [ ]:
#행(열)별 자료 검색 방법 - loc()
#df.loc[행인덱스,열인덱스]
df.loc['홍길동',:]  #df.loc['홍길동']
#type(df.loc['홍길동'])
#df.loc['홍길동',['나이','키']]

나이        15
키      160.5
사는곳       서울
Name: 홍길동, dtype: object

In [ ]:
#행별 자료 검색 방법 - 행으로 인덱스번호로 접근 방법(iloc)
df.iloc[0]

나이        15
키      160.5
사는곳       서울
Name: 홍길동, dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 홍길동 to 박정민
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   나이      5 non-null      int64
 1   키       5 non-null      float64
 2   사는곳     5 non-null      object
dtypes: float64(1), int64(1), object(1)
memory usage: 332.0+ bytes

### DF 생성(2) <- 딕셔너리 구조

In [ ]:
#DataFrame 생성(2) - 딕셔너리 구조
data = {"나이":[15,16,20,19,23],
        "키":[160.5, 158.3, 175.0, 178.4, 185.0],
        "사는곳":["서울","대전","대구","부산","제주"]}

idx = ['홍길동', '이순신', '유관순', '박지훈', '박정민']
df2 = pd.DataFrame(data,
             index = idx)
df2

     나이      키 사는곳
홍길동  15  160.5  서울
이순신  16  158.3  대전
유관순  20  175.0  대구
박지훈  19  178.4  부산
박정민  23  185.0  제주

In [ ]:
import pandas as pd

In [ ]:
#DataFrame 생성(2) - 딕셔너리 구조 실습
# K-pop 아이돌 7명을 대상으로 한 샘플 데이터 (파이썬 딕셔너리 구조)
idol_data = {
    '이름': ['장원영', '카리나', '차은우', '민지', '정국', '뷔', '제니'],
    '학교': ['청담고', '팔달고', '수리고', '신사고', '부산고', '거창고', '강남고'],
    '키': [173, 168, 183, 169, 178, 179, 163],
    '국어': [90, 85, 100, 88, 75, 82, 95],
    '영어': [100, 90, 95, 92, 80, 85, 100],
    '수학': [85, 100, 100, 78, 70, 65, 100],
    '과학': [88, 84, 98, 85, 72, 70, 92],
    '사회': [92, 88, 96, 90, 85, 78, 94],
    'SW특기': ['Python', 'Java', 'C++', 'JavaScript', 'SQL',None,None ]
}

In [ ]:
idol_data['이름']
#type(idol_data)

['장원영', '카리나', '차은우', '민지', '정국', '뷔', '제니']

In [ ]:
#DataFrame 생성
df3 = pd.DataFrame(idol_data)
df3

    이름   학교    키   국어   영어   수학  과학  사회        SW특기
0  장원영  청담고  173   90  100   85  88  92      Python
1  카리나  팔달고  168   85   90   92  84  88        Java
2  차은우  수리고  183  100   95  100  98  96         C++
3   민지  신사고  169   88   92   78  85  90  JavaScript
4   정국  부산고  178   75   80   70  72  85         SQL
5    뷔  거창고  179   82   85   65  70  78        None
6   제니  강남고  163   95  100   88  92  94        None

In [ ]:
#데이터 접근
df3['이름']

0    장원영
1    카리나
2    차은우
3     민지
4     정국
5      뷔
6     제니
Name: 이름, dtype: object

In [ ]:
df3[['이름','키']]

    이름    키
0  장원영  173
1  카리나  168
2  차은우  183
3   민지  169
4   정국  178
5    뷔  179
6   제니  163

### DF Index(정렬포함)

*   Index생성/삭제
*   Index 정렬 sort_index()

*   🎁일반컬럼 정렬 sort_values()

In [ ]:
# 데이터 프레임 생성 - 별도의 인덱스 생성
import pandas as pd

idol_data = {
    '이름': ['장원영', '카리나', '차은우', '민지', '정국', '뷔', '제니'],
    '학교': ['청담고', '팔달고', '수리고', '신사고', '부산고', '거창고', '강남고'],
    '키': [173, 168, 183, 169, 178, 179, 163],
    '국어': [90, 85, 100, 88, 75, 82, 95],
    '영어': [100, 90, 95, 92, 80, 85, 100],
    '수학': [85, 100, 100, 78, 70, 65, 100],
    '과학': [88, 84, 98, 85, 72, 70, 92],
    '사회': [92, 88, 96, 90, 85, 78, 94],
    'SW특기': ['Python', 'Java', 'C++', 'JavaScript', 'SQL',None,None ]
}

df4 = pd.DataFrame(idol_data, index = ['1번','2번','3번','4번','5번','6번','7번'])
df4

     이름   학교    키   국어   영어   수학  과학  사회        SW특기
1번  장원영  청담고  173   90  100   85  88  92      Python
2번  카리나  팔달고  168   85   90  100  84  88        Java
3번  차은우  수리고  183  100   95  100  98  96         C++
4번   민지  신사고  169   88   92   78  85  90  JavaScript
5번   정국  부산고  178   75   80   70  72  85         SQL
6번    뷔  거창고  179   82   85   65  70  78        None
7번   제니  강남고  163   95  100  100  92  94        None

In [ ]:
# 데이터프레임 인덱스 확인
df4.index

Index(['1번', '2번', '3번', '4번', '5번', '6번', '7번'], dtype='object')

In [ ]:
df4

     이름   학교    키   국어   영어   수학  과학  사회        SW특기
1번  장원영  청담고  173   90  100   85  88  92      Python
2번  카리나  팔달고  168   85   90   92  84  88        Java
3번  차은우  수리고  183  100   95  100  98  96         C++
4번   민지  신사고  169   88   92   78  85  90  JavaScript
5번   정국  부산고  178   75   80   70  72  85         SQL
6번    뷔  거창고  179   82   85   65  70  78        None
7번   제니  강남고  163   95  100   88  92  94        None

In [ ]:
# 인덱스명 설정
df4.index.name = ' 지원번호'
df4

        이름   학교    키   국어   영어   수학  과학  사회        SW특기
 지원번호
1번     장원영  청담고  173   90  100   85  88  92      Python
2번     카리나  팔달고  168   85   90   92  84  88        Java
3번     차은우  수리고  183  100   95  100  98  96         C++
4번      민지  신사고  169   88   92   78  85  90  JavaScript
5번      정국  부산고  178   75   80   70  72  85         SQL
6번       뷔  거창고  179   82   85   65  70  78        None
7번      제니  강남고  163   95  100   88  92  94        None

In [ ]:
#인덱스 초기화
df4.reset_index()   #DF인덱스가 drop된 것은 아님.

   지원번호   이름   학교    키   국어   영어   수학  과학  사회        SW특기
0    1번  장원영  청담고  173   90  100   85  88  92      Python
1    2번  카리나  팔달고  168   85   90   92  84  88        Java
2    3번  차은우  수리고  183  100   95  100  98  96         C++
3    4번   민지  신사고  169   88   92   78  85  90  JavaScript
4    5번   정국  부산고  178   75   80   70  72  85         SQL
5    6번    뷔  거창고  179   82   85   65  70  78        None
6    7번   제니  강남고  163   95  100   88  92  94        None

In [ ]:
df4 = df4.reset_index(drop=True)  #df4.reset_index(drop=True, inplace=True)
df4

    이름   학교    키   국어   영어   수학  과학  사회        SW특기
0  장원영  청담고  173   90  100   85  88  92      Python
1  카리나  팔달고  168   85   90  100  84  88        Java
2  차은우  수리고  183  100   95  100  98  96         C++
3   민지  신사고  169   88   92   78  85  90  JavaScript
4   정국  부산고  178   75   80   70  72  85         SQL
5    뷔  거창고  179   82   85   65  70  78        None
6   제니  강남고  163   95  100  100  92  94        None

In [ ]:
#인덱스 설정 - 지정한 컬럼으로 index 지정
df4.set_index('이름',inplace=True)
df4

      학교    키   국어   영어   수학  과학  사회        SW특기
이름
장원영  청담고  173   90  100   85  88  92      Python
카리나  팔달고  168   85   90  100  84  88        Java
차은우  수리고  183  100   95  100  98  96         C++
민지   신사고  169   88   92   78  85  90  JavaScript
정국   부산고  178   75   80   70  72  85         SQL
뷔    거창고  179   82   85   65  70  78        None
제니   강남고  163   95  100  100  92  94        None

In [ ]:
#데이터프레임 - 인덱스를 기준으로 정렬
df4.sort_index()  #인덱스로 오름차순

      학교    키   국어   영어   수학  과학  사회        SW특기
이름
민지   신사고  169   88   92   78  85  90  JavaScript
뷔    거창고  179   82   85   65  70  78        None
장원영  청담고  173   90  100   85  88  92      Python
정국   부산고  178   75   80   70  72  85         SQL
제니   강남고  163   95  100  100  92  94        None
차은우  수리고  183  100   95  100  98  96         C++
카리나  팔달고  168   85   90  100  84  88        Java

In [ ]:
#Default: ascending=True
df4.sort_index(ascending=False) # 내림차순

     이름   학교    키   국어   영어   수학  과학  사회        SW특기
7번   제니  강남고  163   95  100   88  92  94        None
6번    뷔  거창고  179   82   85   65  70  78        None
5번   정국  거창고  178   75   80   70  72  85         SQL
4번   민지  거창고  169   88   92   78  85  90  JavaScript
3번  차은우  수리고  183  100   95  100  98  96         C++
2번  카리나  수리고  168   85   90   92  84  88        Java
1번  장원영  청담고  173   90  100   85  88  92      Python

In [ ]:
#🎃🎃🎃(참고) 인덱스 아닌 컬럼으로 정렬(인덱스 컬럼 포함)🎃🎃🎃
#(참고) 인덱스 아닌 컬럼으로 정렬(인덱스 컬럼 포함)
#sorted_df = df.sort_values(by=['Score', 'Name'], ascending=[False, True])
df4.sort_values(by=['이름','학교'], ascending=False)      #ascending=True 오름차순(Default)

      학교    키   국어   영어   수학  과학  사회        SW특기
이름
카리나  팔달고  168   85   90  100  84  88        Java
차은우  수리고  183  100   95  100  98  96         C++
제니   강남고  163   95  100  100  92  94        None
정국   부산고  178   75   80   70  72  85         SQL
장원영  청담고  173   90  100   85  88  92      Python
뷔    거창고  179   82   85   65  70  78        None
민지   신사고  169   88   92   78  85  90  JavaScript

In [ ]:
#국어 점수는 오름차순, 수학 점수는 내림차순
df4.sort_values(by=['수학', '국어'], ascending=[True,False])

      학교    키   국어   영어   수학  과학  사회        SW특기
이름
뷔    거창고  179   82   85   65  70  78        None
정국   부산고  178   75   80   70  72  85         SQL
민지   신사고  169   88   92   78  85  90  JavaScript
장원영  청담고  173   90  100   85  88  92      Python
차은우  수리고  183  100   95  100  98  96         C++
제니   강남고  163   95  100  100  92  94        None
카리나  팔달고  168   85   90  100  84  88        Java

In [ ]:
#특정 컬럼만 정렬해서 보기(Series형태로 보기)
df4[['국어','키']].sort_values(by=['키','국어'])   #인덱스 컬럼이  특정 컬럼에 포함 되면 안됨.

      국어    키
이름
제니    95  163
카리나   85  168
민지    88  169
장원영   90  173
정국    75  178
뷔     82  179
차은우  100  183

### DF 활용 (Skip 가능)

In [ ]:
# 특정 컬럼만 조회하기
df4[['이름','SW특기','학교']]

     이름        SW특기   학교
1번  장원영      Python  청담고
2번  카리나        Java  수리고
3번  차은우         C++  수리고
4번   민지  JavaScript  거창고
5번   정국         SQL  거창고
6번    뷔        None  거창고
7번   제니        None  강남고

In [ ]:
#특정 컬럼만으로 데이터 프레임 생성, 특정 순서로 생성
df5 = pd.DataFrame(idol_data,  columns=['이름','SW특기','학교'])
df5

    이름        SW특기   학교
0  장원영      Python  청담고
1  카리나        Java  수리고
2  차은우         C++  수리고
3   민지  JavaScript  거창고
4   정국         SQL  거창고
5    뷔        None  거창고
6   제니        None  강남고

In [ ]:
# 결측치를 특정 값으로 채우기 : .fillna()
df4['SW특기'] = df4['SW특기'].fillna('C')
df4

      학교    키   국어   영어   수학  과학  사회        SW특기
이름
장원영  청담고  173   90  100   85  88  92      Python
카리나  팔달고  168   85   90   92  84  88        Java
차은우  수리고  183  100   95  100  98  96         C++
민지   신사고  169   88   92   78  85  90  JavaScript
정국   부산고  178   75   80   70  72  85         SQL
뷔    거창고  179   82   85   65  70  78           C
제니   강남고  163   95  100   88  92  94           C

In [ ]:
#특정 컬럼의 특정 값을 변경하기(2) -인덱스 컬럼 제외
df4.reset_index(inplace=True)
df4.loc[df4['이름'] == '카리나', '이름'] = '박지원'
df4

    이름   학교    키   국어   영어   수학  과학  사회        SW특기
0  장원영  청담고  173   90  100   85  88  92      Python
1  박지원  팔달고  168   85   90   92  84  88        Java
2  차은우  수리고  183  100   95  100  98  96         C++
3   민지  신사고  169   88   92   78  85  90  JavaScript
4   정국  부산고  178   75   80   70  72  85         SQL
5    뷔  거창고  179   82   85   65  70  78          C+
6   제니  강남고  163   95  100   88  92  94          C+

## 3️⃣파일로 저장하기
csv.excel,txt

In [ ]:
import pandas as pd
idol_data = {
    '이름': ['장원영', '카리나', '차은우', '민지', '정국', '뷔', '제니'],
    '학교': ['청담고', '팔달고', '수리고', '신사고', '부산고', '거창고', '강남고'],
    '키': [173, 168, 183, 169, 178, 179, 163],
    '국어': [90, 85, 100, 88, 75, 82, 95],
    '영어': [100, 90, 95, 92, 80, 85, 100],
    '수학': [85, 92, 100, 78, 70, 65, 88],
    '과학': [88, 84, 98, 85, 72, 70, 92],
    '사회': [92, 88, 96, 90, 85, 78, 94],
    'SW특기': ['Python', 'Java', 'C++', 'JavaScript', 'SQL',None,None ]
}
df = pd.DataFrame(idol_data, index = ['1번','2번','3번','4번','5번','6번','7번'])

In [ ]:
#csv 파일로 저장 - # colab 저장소에 파일 저장
df.to_csv('k-scores.csv',encoding='utf-8-sig')  #/content/k-scores.csv

In [ ]:
df.to_csv('k-scores2.csv',encoding='utf-8-sig',index=False)

In [ ]:
#엑셀로 저장하기
df.to_excel('k-scores.xlsx')

In [ ]:
#텍스트파일로 저장하기
df.to_csv('k-scores.txt',sep='\t') #tab으로 구분된 파일

## 4️⃣파일에서 데이터 불러오기

* 파일의 데이터를 불러와 데이터프레임 객체로 생성
* pd.read_csv(파일명)


#### 🥕colab 저장소에 파일 업로드. 런타임이 유지되는 동안만 파일 유지
     data1 = '/content/k-scores.csv'
#### 🥕구글 드라이브 마운트. 런타임이 종료되어도 파일 유지
     data2 = '/content/drive/MyDrive/##p_data/k-scores.csv'
#### 🥕깃허브 저장소 연동
     data3 ='https://raw.githubusercontent.com/sseegg300/data/refs/heads/main/k-scores.csv'

### [1] colab저장소 활용 방법
-런타임이 유지되는 동안만 파일 유지

(1) 직접 업로드 하기

(2) 명령어로 업로드 하기 files.upload()

In [ ]:
from google.colab import files
upload = files.upload()

Saving k-scores.csv to k-scores.csv

(3) 명령어로 업로드 하기 !gdown (파일위치)
*  (파일위치)는 https://drive.google.com/uc?id={FILE_ID} 형식
*  [공유] > [링크 복사] :권한이 '링크가 있는 모든 사용자'로 설정
*   공유 URL에서 /d/와 /view 사이에 있는 문자열:{FILE_ID}

In [ ]:
!gdown https://drive.google.com/uc?id=1nBVl2_OpAvRph_piCk6SsmjuM7DBOOMH

Downloading...
From: https://drive.google.com/uc?id=1nBVl2_OpAvRph_piCk6SsmjuM7DBOOMH
To: /content/k-scores.csv
100% 505/505 [00:00<00:00, 1.65MB/s]

In [ ]:
!ls

In [ ]:
import os
print(os.getcwd()) # 현재 작업 디렉토리 확인

/content

In [ ]:
import pandas as pd

In [ ]:
data1 = '/content/k-scores.csv'
df = pd.read_csv(data1)
#type(df)
df

    이름   학교  학년    키   국어   영어   수학  과학  사회          특기 동아리
0  장원영  청담고   1  173   90  100   85  88  92        영상편집  댄스
1  카리나  팔달고   2  168   85   90   92  84  88     이모티콘 제작  실험
2  차은우  수리고   2  183  100   95  100  98  96          보컬  실험
3   민지  부산고   3  169   88   92   78  85  90      v게임 제작  댄스
4   정국  부산고   1  178   75   80   70  72  85  C++/Python  독서
5    뷔  청담고   3  179   82   85   65  70  78    수학 문제 풀이  독서
6   제니  청담고   3  163   95  100   88  92  94      3D 모델링  댄스

###[2] 구글 드라이브 마운트
   - 런타임이 종료되어도 파일 유지

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#unmout 방법
from google.colab import drive
drive.flush_and_unmount()

Drive not mounted, so nothing to flush and unmount.

In [ ]:
import os
print(os.getcwd())

/content

In [ ]:
# 데이터프레임 생성
data2 ='/content/drive/MyDrive/##p_data/k-scores.csv'

df = pd.read_csv(data2)

In [ ]:
df

        이름     국어   영어     수학
0     kate  100.0   90   95.0
1   olivia   90.0   80   75.0
2     emma   95.0  100  100.0
3   sophia  100.0  100  100.0
4      amy    NaN   35   60.0
5    james   70.0   75   65.0
6   daniel   80.0   90   55.0
7    peter   50.0   60    NaN
8    kevin  100.0  100   90.0
9     jack   90.0   95   70.0
10   james   70.0   75   65.0

### [3] 깃허브 활용

In [ ]:
# 데이터프레임 생성
data3 = 'https://raw.githubusercontent.com/sseegg300/data/refs/heads/main/k-scores.csv'
df = pd.read_csv(data3)
df

    이름   학교  학년    키     국어     영어     수학    과학  사회          특기 동아리
0  장원영  청담고   1  173   90.0  100.0   85.0  88.0  92        영상편집  댄스
1  카리나  팔달고   2  168   85.0   90.0   92.0   NaN  88     이모티콘 제작  실험
2  차은우  수리고   2  183  100.0   95.0  100.0  98.0  96          보컬  실험
3   민지  부산고   3  169   92.0    NaN    NaN  85.0  90       게임 제작  댄스
4   정국  부산고   1  178   75.0   80.0    NaN  72.0  85  C++/Python  독서
5    뷔  청담고   3  179   82.0   85.0   65.0  70.0  78    수학 문제 풀이  독서
6   제니  청담고   3  163    NaN  100.0    NaN  92.0  94      3D 모델링  댄스

## 5️⃣데이터 확인


*  행추출
 `.head(n)`  `.tail(n)`
*  열추출
 `데이터프레임명[컬럼명]` `데이터프레임명[[컬럼명리스트]]`
*   요약통계 `.describe()`
*   기본정보 `.info()`

*   결측치확인및 처리 `.isnull().sum()` `.dropna()` `.fillna(값)`

### 기본(상위,하위) 행 추출하기

* `.head(n)` : 상위 n개 행 보기

* `.tail(n)` : 하위 n개 행 보기

In [ ]:
import pandas as pd
idol_data = {
    '이름': ['장원영', '카리나', '차은우', '민지', '정국', '뷔', '제니'],
    '학교': ['청담고', '수리고', '수리고', '거창고', '거창고', '거창고', '강남고'],
    '키': [173, 168, 183, 169, None, 179, 163],
    '국어': [90, 85, 100, 88, 75, 82, 95],
    '영어': [100, 90, 95, None, 80, None, 100],
    '수학': [85, 92, 100, None, 70, 65, 88],
    '과학': [88, 84, 98, 85, 72, 70, 92],
    '사회': [92, 88, 96, 90, 85, 78, 94],
    'SW특기': ['Python', 'Java', 'C++', 'JavaScript', 'SQL',None,None ],
    '진로': ['AI개발','AI개발','데이터과학','PD','DB관리','디렉터','마케터']
}
df = pd.DataFrame(idol_data, index = ['1번','2번','3번','4번','5번','6번','7번'])
df

     이름   학교      키   국어     영어     수학  과학  사회        SW특기     진로
1번  장원영  청담고  173.0   90  100.0   85.0  88  92      Python   AI개발
2번  카리나  수리고  168.0   85   90.0   92.0  84  88        Java   AI개발
3번  차은우  수리고  183.0  100   95.0  100.0  98  96         C++  데이터과학
4번   민지  거창고  169.0   88    NaN    NaN  85  90  JavaScript     PD
5번   정국  거창고    NaN   75   80.0   70.0  72  85         SQL   DB관리
6번    뷔  거창고  179.0   82    NaN   65.0  70  78        None    디렉터
7번   제니  강남고  163.0   95  100.0   88.0  92  94        None    마케터

In [ ]:
#상위 5개 데이터 확인
df.head(5)

    이름   학교  학년    키     국어     영어     수학    과학  사회          특기 동아리
0  장원영  청담고   1  173   90.0  100.0   85.0  88.0  92        영상편집  댄스
1  카리나  팔달고   2  168   85.0   90.0   92.0   NaN  88     이모티콘 제작  실험
2  차은우  수리고   2  183  100.0   95.0  100.0  98.0  96          보컬  실험
3   민지  부산고   3  169   92.0    NaN    NaN  85.0  90       게임 제작  댄스
4   정국  부산고   1  178   75.0   80.0    NaN  72.0  85  C++/Python  독서

In [ ]:
#하위 5개 데이터 확인
df.tail(5)

    이름   학교  학년    키     국어     영어     수학    과학  사회          특기 동아리
2  차은우  수리고   2  183  100.0   95.0  100.0  98.0  96          보컬  실험
3   민지  부산고   3  169   92.0    NaN    NaN  85.0  90       게임 제작  댄스
4   정국  부산고   1  178   75.0   80.0    NaN  72.0  85  C++/Python  독서
5    뷔  청담고   3  179   82.0   85.0   65.0  70.0  78    수학 문제 풀이  독서
6   제니  청담고   3  163    NaN  100.0    NaN  92.0  94      3D 모델링  댄스

### 요약통계량 보기
* `.describe()`
*   컬럼별로  데이터의 갯수,평균,표준편차,최소/최대값등의 정보(계산이 가능한 컬럼을 대상)

In [ ]:
df.describe()

,학년,키,국어,영어,수학,과학,사회
count,7.000000,7.000000,6.000000,6.000000,4.000000,6.000000,7.000000
mean,2.142857,173.285714,87.333333,91.666667,85.500000,84.166667,89.000000
std,0.899735,7.087884,8.664102,8.164966,14.977761,11.107055,6.082763
min,1.000000,163.000000,75.000000,80.000000,65.000000,70.000000,78.000000
25%,1.500000,168.500000,82.750000,86.250000,80.000000,75.250000,86.500000
50%,2.000000,173.000000,87.500000,92.500000,88.500000,86.500000,90.000000
75%,3.000000,178.500000,91.500000,98.750000,94.000000,91.000000,93.000000
max,3.000000,183.000000,100.000000,100.000000,100.000000,98.000000,96.000000

### 데이터프레임 정보 보기
* `.info()`

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      7 non-null      object
 1   학교      7 non-null      object
 2   학년      7 non-null      int64
 3   키       7 non-null      int64
 4   국어      6 non-null      float64
 5   영어      6 non-null      float64
 6   수학      4 non-null      float64
 7   과학      6 non-null      float64
 8   사회      7 non-null      int64
 9   특기      7 non-null      object
 10  동아리     7 non-null      object
dtypes: float64(4), int64(3), object(4)
memory usage: 748.0+ bytes

### 컬럼별 결측치 확인/처리하기
* `.isnull().sum()`

* `.dropna()` : 결측치가 있는 행 삭제
* `.fillna(값)` : 결측치를 다른 값으로 대체

In [ ]:
df

     이름   학교      키   국어     영어     수학  과학  사회        SW특기
1번  장원영  청담고  173.0   90  100.0   85.0  88  92      Python
2번  카리나  수리고  168.0   85   90.0   92.0  84  88        Java
3번  차은우  수리고  183.0  100   95.0  100.0  98  96         C++
4번   민지  거창고  169.0   88    NaN    NaN  85  90  JavaScript
5번   정국  거창고    NaN   75   80.0   70.0  72  85         SQL
6번    뷔  거창고  179.0   82    NaN   65.0  70  78        None
7번   제니  강남고  163.0   95  100.0   88.0  92  94        None

In [ ]:
#결측치 데이터 확인
df.isnull().sum()

이름     0
학교     0
학년     0
키      0
국어     1
영어     1
수학     3
과학     1
사회     0
특기     0
동아리    0
dtype: int64

In [ ]:
# 결측치 데이터 채우기 filna()
# df.fillna('없음',inplace=True)        #바로 적용
df.fillna('없음')                           #전체컬럼을 ''로 반영됨.

    이름   학교  학년    키     국어     영어     수학    과학  사회          특기 동아리
0  장원영  청담고   1  173   90.0  100.0   85.0  88.0  92        영상편집  댄스
1  카리나  팔달고   2  168   85.0   90.0   92.0    없음  88     이모티콘 제작  실험
2  차은우  수리고   2  183  100.0   95.0  100.0  98.0  96          보컬  실험
3   민지  부산고   3  169   92.0     없음     없음  85.0  90       게임 제작  댄스
4   정국  부산고   1  178   75.0   80.0     없음  72.0  85  C++/Python  독서
5    뷔  청담고   3  179   82.0   85.0   65.0  70.0  78    수학 문제 풀이  독서
6   제니  청담고   3  163     없음  100.0     없음  92.0  94      3D 모델링  댄스

In [ ]:
#특정 컬럼만 null 값을 변경할때
df['수학'].fillna('없음',inplace=True)
df

    이름   학교  학년    키     국어     영어     수학    과학  사회          특기 동아리
0  장원영  청담고   1  173   90.0  100.0   85.0  88.0  92        영상편집  댄스
1  카리나  팔달고   2  168   85.0   90.0   92.0   NaN  88     이모티콘 제작  실험
2  차은우  수리고   2  183  100.0   95.0  100.0  98.0  96          보컬  실험
3   민지  부산고   3  169   92.0    NaN     없음  85.0  90       게임 제작  댄스
4   정국  부산고   1  178   75.0   80.0     없음  72.0  85  C++/Python  독서
5    뷔  청담고   3  179   82.0   85.0   65.0  70.0  78    수학 문제 풀이  독서
6   제니  청담고   3  163    NaN  100.0     없음  92.0  94      3D 모델링  댄스

In [ ]:
#numpy로 NaN 채우기
import numpy as np
df['진로'] = np.nan
df

     이름   학교      키   국어     영어     수학  과학  사회        SW특기  진로
1번  장원영  청담고  173.0   90  100.0   85.0  88  92      Python NaN
2번  카리나  수리고  168.0   85   90.0   92.0  84  88        Java NaN
3번  차은우  수리고  183.0  100   95.0  100.0  98  96         C++ NaN
4번   민지  거창고  169.0   88    NaN    NaN  85  90  JavaScript NaN
5번   정국  거창고    NaN   75   80.0   70.0  72  85         SQL NaN
6번    뷔  거창고  179.0   82    NaN   65.0  70  78        None NaN
7번   제니  강남고  163.0   95  100.0   88.0  92  94        None NaN

In [ ]:
df.isnull().sum()

In [ ]:
#특정 컬럼의 결측치 데이터만 채우기
df['진로'].fillna('없음',inplace=True)
df

/tmp/ipykernel_1065/2161073608.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['진로'].fillna('없음',inplace=True)

     이름   학교      키   국어     영어     수학  과학  사회        SW특기  진로
1번  장원영  청담고  173.0   90  100.0   85.0  88  92      Python  없음
2번  카리나  수리고  168.0   85   90.0   92.0  84  88        Java  없음
3번  차은우  수리고  183.0  100   95.0  100.0  98  96         C++  없음
4번   민지  거창고  169.0   88    NaN    NaN  85  90  JavaScript  없음
5번   정국  거창고    NaN   75   80.0   70.0  72  85         SQL  없음
6번    뷔  거창고  179.0   82    NaN   65.0  70  78        None  없음
7번   제니  강남고  163.0   95  100.0   88.0  92  94        None  없음

In [ ]:
# 결측치 데이터 삭제하기  dropna()
df.dropna()  #전체 데이터 중에서 NaN를 포함한 데이터 삭제
#df.dropna(inplace=True)

    이름   학교  학년    키     국어     영어     수학    과학  사회          특기 동아리
0  장원영  청담고   1  173   90.0  100.0   85.0  88.0  92        영상편집  댄스
2  차은우  수리고   2  183  100.0   95.0  100.0  98.0  96          보컬  실험
4   정국  부산고   1  178   75.0   80.0     없음  72.0  85  C++/Python  독서
5    뷔  청담고   3  179   82.0   85.0   65.0  70.0  78    수학 문제 풀이  독서

In [ ]:
# dropna() 함수 심화작업
#axis : index(0) or columns(1)  / how : any(Default) or all
#index즉 행을 삭제 하는 경우, any:하나라도 Nan가 있는 경우
df.dropna(axis='index', how = 'any')

     이름   학교      키   국어     영어     수학  과학  사회    SW특기  진로
1번  장원영  청담고  173.0   90  100.0   85.0  88  92  Python  없음
2번  카리나  수리고  168.0   85   90.0   92.0  84  88    Java  없음
3번  차은우  수리고  183.0  100   95.0  100.0  98  96     C++  없음

In [ ]:
#import numpy as np
df['진로']=np.nan
df

     이름   학교      키   국어     영어     수학  과학  사회        SW특기  진로
1번  장원영  청담고  173.0   90  100.0   85.0  88  92      Python NaN
2번  카리나  수리고  168.0   85   90.0   92.0  84  88        Java NaN
3번  차은우  수리고  183.0  100   95.0  100.0  98  96         C++ NaN
4번   민지  거창고  169.0   88    NaN    NaN  85  90  JavaScript NaN
5번   정국  거창고    NaN   75   80.0   70.0  72  85         SQL NaN
6번    뷔  거창고  179.0   82    NaN   65.0  70  78        None NaN
7번   제니  강남고  163.0   95  100.0   88.0  92  94        None NaN

In [ ]:
df.dropna(axis='columns', how = 'all')

     이름   학교      키   국어     영어     수학  과학  사회        SW특기
1번  장원영  청담고  173.0   90  100.0   85.0  88  92      Python
2번  카리나  수리고  168.0   85   90.0   92.0  84  88        Java
3번  차은우  수리고  183.0  100   95.0  100.0  98  96         C++
4번   민지  거창고  169.0   88    NaN    NaN  85  90  JavaScript
5번   정국  거창고    NaN   75   80.0   70.0  72  85         SQL
6번    뷔  거창고  179.0   82    NaN   65.0  70  78        None
7번   제니  강남고  163.0   95  100.0   88.0  92  94        None

In [ ]:
df

     이름   학교      키   국어     영어     수학  과학  사회        SW특기  진로
1번  장원영  청담고  173.0   90  100.0   85.0  88  92      Python  없음
2번  카리나  수리고  168.0   85   90.0   92.0  84  88        Java  없음
3번  차은우  수리고  183.0  100   95.0  100.0  98  96         C++  없음
4번   민지  거창고  169.0   88    NaN    NaN  85  90  JavaScript  없음
5번   정국  거창고    NaN   75   80.0   70.0  72  85         SQL  없음
6번    뷔  거창고  179.0   82    NaN   65.0  70  78        None  없음
7번   제니  강남고  163.0   95  100.0   88.0  92  94        None  없음

### 추가 정보 확인
* `.columns`
* `.index`
* `.shape`

In [ ]:
df.columns

Index(['이름', '학교', '키', '국어', '영어', '수학', '과학', '사회', 'SW특기'], dtype='object')

In [ ]:
df.index

Index(['1번', '2번', '3번', '4번', '5번', '6번', '7번'], dtype='object')

In [ ]:
df.shape  #(row,column)

(7, 9)

### Series별 확인
* `데이터프레임명[컬럼명].함수명`

In [ ]:
df['국어']
df['국어'].describe()

count      7.000000
mean      87.857143
std        8.275034
min       75.000000
25%       83.500000
50%       88.000000
75%       92.500000
max      100.000000
Name: 국어, dtype: float64

In [ ]:
print(f'최저 국어점수 : {df['국어'].min()}점')
print(df['국어'].max())

최저 국어점수 : 75점
100

In [ ]:
print(df['국어'].nlargest(3))  # 점수가 높은 3명
print(df['국어'].mean())
print(df['국어'].sum())

3번    100
7번     95
1번     90
Name: 국어, dtype: int64
87.85714285714286
615

In [ ]:
df['SW특기'].count()   #결측치 제외

np.int64(5)

In [ ]:
df['학교'].unique()

array(['청담고', '수리고', '거창고', '강남고'], dtype=object)

## 6️⃣데이터 선택


*  컬럼선택 - 컬럼명 & 인덱스 번호
*  슬라이싱
*  loc() /iloc()
*  조건에 따른 데이터 선택

### 컬럼선택

*   컬럼명으로 선택
*   인덱스 번호로 선택

*   `데이터프레임명[컬럼명(인덱스번호)]` `데이터프레임명[[컬럼명(인덱스번호)리스트]]`

In [ ]:
df['이름']
df[['이름','학교']]

     이름   학교
1번  장원영  청담고
2번  카리나  수리고
3번  차은우  수리고
4번   민지  거창고
5번   정국  거창고
6번    뷔  거창고
7번   제니  강남고

In [ ]:
# 우측 마지막 컬럼 값
df.columns

Index(['이름', '학교', '키', '국어', '영어', '수학', '과학', '사회', 'SW특기', '진로'], dtype='object')

In [ ]:
#컬럼명을 알아내는 방법
print(df.columns[-1])            #결과type:str
print(df.columns[[0,-1]])        #결과type:pandas.core.indexes.base.Index /object

진로
Index(['이름', '진로'], dtype='object')

In [ ]:
#컬럼명을 알아내고 다시 df[]로 DataFrame 형태로 보기.
df[df.columns[-1]]       #df['SW특기']
df[df.columns[[0,-1]]]   #df[['이름','SW특기']]

     이름        SW특기
번호
1번  장원영      Python
2번  카리나        Java
3번  차은우         CC+
4번   민지  JavaScript
5번   정국         SQL
6번    뷔         NaN
7번   제니         NaN

### 슬라이싱

In [ ]:
#특정 구간의 행 구하기
df[0:4]
df[-4:-1]
df[2:4]
df[:3]  #0~2
df[3:]  #3(4번째)~끝

    이름   학교    키  국어   영어  수학  과학  사회        SW특기
4번  민지  거창고  169  88   92  78  85  90  JavaScript
5번  정국  거창고  178  75   80  70  72  85         SQL
6번   뷔  거창고  179  82   85  65  70  78        None
7번  제니  강남고  163  95  100  88  92  94        None

In [ ]:
df['이름'][2:4]   # 2~3까지의 이름
df[['이름','SW특기']][2:4] # 2~3까지의 이름.SW특기

     이름        SW특기
3번  차은우         C++
4번   민지  JavaScript

In [ ]:
#인덱스 정수로 슬라이싱하기
df[df.columns[[0,-1]]][2:4]

     이름        SW특기
3번  차은우         C++
4번   민지  JavaScript

### loc(행인덱스명,열명)
*   원하는 row 에서 원하는 col 선택(이름 활용)
*   행명은 인덱스컬럼의 해당 행명이여야함.

In [ ]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/sseegg300/data/refs/heads/main/k-scores.csv')
df['번호']=['1번','2번','3번','4번','5번','6번','7번']
df.set_index('번호', inplace=True)

# url = 'https://raw.githubusercontent.com/sseegg300/data/refs/heads/main/k-scores.csv'
# df = pd.read_csv(url).assign(번호=['1번','2번','3번','4번','5번','6번','7번']).set_index('번호')
df

     이름   학교  학년    키     국어     영어     수학    과학  사회          특기 동아리
번호
1번  장원영  청담고   1  173   90.0  100.0   85.0  88.0  92        영상편집  댄스
2번  카리나  팔달고   2  168   85.0   90.0   92.0   NaN  88     이모티콘 제작  실험
3번  차은우  수리고   2  183  100.0   95.0  100.0  98.0  96          보컬  실험
4번   민지  부산고   3  169   92.0    NaN    NaN  85.0  90       게임 제작  댄스
5번   정국  부산고   1  178   75.0   80.0    NaN  72.0  85  C++/Python  독서
6번    뷔  청담고   3  179   82.0   85.0   65.0  70.0  78    수학 문제 풀이  독서
7번   제니  청담고   3  163    NaN  100.0    NaN  92.0  94      3D 모델링  댄스

In [ ]:
df.loc['2번']  #2번 학생의 전체 데이터

이름       카리나
학교       팔달고
학년         2
키        168
국어        85
영어        90
수학        92
과학        84
사회        88
SW특기    Java
동아리       실험
Name: 2번, dtype: object

In [ ]:
df.loc['2번','이름']           #2번 학생의 이름 데이터
df.loc['2번',['이름','국어']]   #2번 학생의 이름과 국어성적 데이터

이름    카리나
국어     85
Name: 2번, dtype: object

In [ ]:
df.loc[['2번','3번'],['국어','영어','수학']]  #2,3,번 학생의 국영수 성적

     국어  영어   수학
번호
2번   85  90   92
3번  100  95  100

In [ ]:
#1번부터5번(행) / '국어'부터'수학'가지
#(주의) 슬라이싱 할때 인덱스명으로 할때는 n-1이 적용 되지 않음.

df.loc['1번':'5번','국어':'수학']

       국어     영어     수학
번호
1번   90.0  100.0   85.0
2번   85.0   90.0   92.0
3번  100.0   95.0  100.0
4번   92.0    NaN    NaN
5번   75.0   80.0    NaN

In [ ]:
#(참고) 인덱스 컬럼이 아닌 일반 커럶의 값으로 데이터 선택
df[df['국어'] > 90]                          #전체 컬럼
df[df['국어'] > 90][['이름','국어']]          #이름,국어만

     이름     국어
번호
3번  차은우  100.0
4번   민지   92.0

### iloc(행번호,열번호)  
*   inteager-loc()
*   원하는 row 에서 원하는 col 선택(위치 활용)

In [ ]:
df.iloc[0]
df.iloc[3]
df.iloc[0:4]

     이름   학교  학년    키   국어   영어   수학  과학  사회        SW특기 동아리
번호
1번  장원영  청담고   1  173   90  100   85  88  92      Python  댄스
2번  카리나  팔달고   2  168   85   90   92  84  88        Java  실험
3번  차은우  수리고   2  183  100   95  100  98  96      Python  실험
4번   민지  부산고   3  169   88   92   78  85  90  JavaScript  댄스

In [ ]:
df.iloc[0,1]
df.iloc[0,:4]

이름    장원영
학교    청담고
학년      1
키     173
Name: 1번, dtype: object

In [ ]:
df.iloc[[0,1],[0,1,2]] #1,2번 학생의 이름,학교,키

     이름   학교  학년
번호
1번  장원영  청담고   1
2번  카리나  팔달고   2

In [ ]:
df.iloc[:4,3:]   # 슬라이싱할때는 [] 필요 없음.

      키   국어   영어   수학  과학  사회        SW특기 동아리
번호
1번  173   90  100   85  88  92      Python  댄스
2번  168   85   90   92  84  88        Java  실험
3번  183  100   95  100  98  96      Python  실험
4번  169   88   92   78  85  90  JavaScript  댄스

### 조건에 따른 데이터 선택

In [ ]:
df

     이름   학교  학년    키   국어   영어   수학  과학  사회        SW특기 동아리
번호
1번  장원영  청담고   1  173   90  100   85  88  92      Python  댄스
2번  카리나  팔달고   2  168   85   90   92  84  88        Java  실험
3번  차은우  수리고   2  183  100   95  100  98  96      Python  실험
4번   민지  부산고   3  169   88   92   78  85  90  JavaScript  댄스
5번   정국  부산고   1  178   75   80   70  72  85         C++  독서
6번    뷔  청담고   3  179   82   85   65  70  78         NaN  독서
7번   제니  청담고   3  163   95  100   88  92  94         NaN  댄스

In [ ]:
#국어 점수 보기
df['국어']

번호
1번     90
2번     85
3번    100
4번     88
5번     75
6번     82
7번     95
Name: 국어, dtype: int64

In [ ]:
#국어 점수가 90점이 넘는 경우(Boolean)
df['국어'] > 90

번호
1번    False
2번    False
3번     True
4번    False
5번    False
6번    False
7번     True
Name: 국어, dtype: bool

In [ ]:
prize = df['국어'] > 90
print(prize)
df[prize]                   # df[해당 컬럼]  df[해당 조건에 해당하는 모든 컬럼]

1번    False
2번    False
3번     True
4번    False
5번    False
6번    False
7번     True
Name: 국어, dtype: bool

     이름   학교      키   국어     영어     수학  과학  사회  SW특기     진로
3번  차은우  수리고  183.0  100   95.0  100.0  98  96   C++  데이터과학
7번   제니  강남고  163.0   95  100.0   88.0  92  94  None    마케터

In [ ]:
df[df['국어'] > 90]

     이름   학교      키   국어     영어     수학  과학  사회  SW특기     진로
3번  차은우  수리고  183.0  100   95.0  100.0  98  96   C++  데이터과학
7번   제니  강남고  163.0   95  100.0   88.0  92  94  None    마케터

In [ ]:
df[~prize]   #prize 조건이 아님 데이터 보기

     이름   학교  학년    키  국어   영어  수학  과학  사회        SW특기 동아리
번호
1번  장원영  청담고   1  173  90  100  85  88  92      Python  댄스
2번  카리나  팔달고   2  168  85   90  92  84  88        Java  실험
4번   민지  부산고   3  169  88   92  78  85  90  JavaScript  댄스
5번   정국  부산고   1  178  75   80  70  72  85         C++  독서
6번    뷔  청담고   3  179  82   85  65  70  78         NaN  독서

In [ ]:
df.loc[df['국어']> 90,'이름']                  # 국어 점수가 90이 넘는 학생의 이름
df.loc[df['국어']> 90,['이름','수학','영어']]

     이름   수학   영어
번호
3번  차은우  100   95
7번   제니   88  100

In [ ]:
#🎈특정데이터를 선택한 후 수정하는 방법
df.loc[df['SW특기'] == 'Python','SW특기'] = '파이썬'  #바로 commit됨
df

     이름   학교      키   국어     영어     수학  과학  사회        SW특기     진로
1번  장원영  청담고  173.0   90  100.0   85.0  88  92         파이썬   AI개발
2번  카리나  수리고  168.0   85   90.0   92.0  84  88        Java   AI개발
3번  차은우  수리고  183.0  100   95.0  100.0  98  96         C++  데이터과학
4번   민지  거창고  169.0   88    NaN    NaN  85  90  JavaScript     PD
5번   정국  거창고    NaN   75   80.0   70.0  72  85         SQL   DB관리
6번    뷔  거창고  179.0   82    NaN   65.0  70  78        None    디렉터
7번   제니  강남고  163.0   95  100.0   88.0  92  94        None    마케터

## 7️⃣데이터 수정


*  Column 수정 .replace()
*  Column 추가

In [ ]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/sseegg300/data/refs/heads/main/k-scores.csv')
df['번호']=['1번','2번','3번','4번','5번','6번','7번']
df.set_index('번호', inplace=True)

# url = 'https://raw.githubusercontent.com/sseegg300/data/refs/heads/main/k-scores.csv'
# df = pd.read_csv(url).assign(번호=['1번','2번','3번','4번','5번','6번','7번']).set_index('번호')
df

     이름   학교  학년    키     국어     영어     수학    과학  사회          특기 동아리
번호
1번  장원영  청담고   1  173   90.0  100.0   85.0  88.0  92        영상편집  댄스
2번  카리나  팔달고   2  168   85.0   90.0   92.0   NaN  88     이모티콘 제작  실험
3번  차은우  수리고   2  183  100.0   95.0  100.0  98.0  96          보컬  실험
4번   민지  부산고   3  169   92.0    NaN    NaN  85.0  90       게임 제작  댄스
5번   정국  부산고   1  178   75.0   80.0    NaN  72.0  85  C++/Python  독서
6번    뷔  청담고   3  179   82.0   85.0   65.0  70.0  78    수학 문제 풀이  독서
7번   제니  청담고   3  163    NaN  100.0    NaN  92.0  94      3D 모델링  댄스

### Column 수정

In [ ]:
#Column 수정 .replace()
#df['학교'].replace({'팔달고':'팔공고'},inplace=True)
df['학교'].replace({'팔달고':'팔공고','청담고':'국제고'},inplace=True)
df

/tmp/ipykernel_4720/3587735492.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['학교'].replace({'팔달고':'팔공고','청담고':'국제고'},inplace=True)

     이름   학교  학년    키     국어     영어     수학    과학  사회          특기 동아리
번호
1번  장원영  국제고   1  173   90.0  100.0   85.0  88.0  92        영상편집  댄스
2번  카리나  팔공고   2  168   85.0   90.0   92.0   NaN  88     이모티콘 제작  실험
3번  차은우  수리고   2  183  100.0   95.0  100.0  98.0  96          보컬  실험
4번   민지  부산고   3  169   92.0    NaN    NaN  85.0  90       게임 제작  댄스
5번   정국  부산고   1  178   75.0   80.0    NaN  72.0  85  C++/Python  독서
6번    뷔  국제고   3  179   82.0   85.0   65.0  70.0  78    수학 문제 풀이  독서
7번   제니  국제고   3  163    NaN  100.0    NaN  92.0  94      3D 모델링  댄스

In [ ]:
#학교이름을 **고등학교로 수정하기
df['학교'] = df['학교']+'등학교'
df

     이름      학교  학년    키     국어     영어     수학    과학  사회          특기 동아리
번호
1번  장원영  국제고등학교   1  173   90.0  100.0   85.0  88.0  92        영상편집  댄스
2번  카리나  팔공고등학교   2  168   85.0   90.0   92.0   NaN  88     이모티콘 제작  실험
3번  차은우  수리고등학교   2  183  100.0   95.0  100.0  98.0  96          보컬  실험
4번   민지  부산고등학교   3  169   92.0    NaN    NaN  85.0  90       게임 제작  댄스
5번   정국  부산고등학교   1  178   75.0   80.0    NaN  72.0  85  C++/Python  독서
6번    뷔  국제고등학교   3  179   82.0   85.0   65.0  70.0  78    수학 문제 풀이  독서
7번   제니  국제고등학교   3  163    NaN  100.0    NaN  92.0  94      3D 모델링  댄스

### Column 추가

In [ ]:
#null 값을 0로 채우기 - 총점 계산을 하기 위해 null 값을 0점으로 처리
df.fillna(0,inplace=True)

In [ ]:
#Column 추가
#국어+영어+수학+과학+사회 =>총합
df['총점'] = df['국어']+df['영어']+df['수학']+df['과학']+df['사회']
df

     이름   학교  학년    키     국어     영어     수학    과학  사회          특기 동아리     총점
번호
1번  장원영  청담고   1  173   90.0  100.0   85.0  88.0  92        영상편집  댄스  455.0
2번  카리나  팔달고   2  168   85.0   90.0   92.0   0.0  88     이모티콘 제작  실험  355.0
3번  차은우  수리고   2  183  100.0   95.0  100.0  98.0  96          보컬  실험  489.0
4번   민지  부산고   3  169   92.0    0.0    0.0  85.0  90       게임 제작  댄스  267.0
5번   정국  부산고   1  178   75.0   80.0    0.0  72.0  85  C++/Python  독서  312.0
6번    뷔  청담고   3  179   82.0   85.0   65.0  70.0  78    수학 문제 풀이  독서  380.0
7번   제니  청담고   3  163    0.0  100.0    0.0  92.0  94      3D 모델링  댄스  286.0

In [ ]:
#Column 추가(+조건설정)  .loc[]
#총점이 400보다 크면 합격, 아니면 'X'
df.loc[df['총점'] >= 400,'결과'] = '합격'
df.loc[df['총점'] < 400,'결과'] = 'X'
df

,이름,학교,학년,키,국어,영어,수학,과학,사회,특기,동아리,총점,결과
번호,,,,,,,,,,,,,
1번,장원영,국제고등학교,1,173,90.0,100.0,85.0,88.0,92,영상편집,댄스,455.0,합격
2번,카리나,팔공고등학교,2,168,85.0,90.0,92.0,0.0,88,이모티콘 제작,실험,355.0,X
3번,차은우,수리고등학교,2,183,100.0,95.0,100.0,98.0,96,보컬,실험,489.0,합격
4번,민지,부산고등학교,3,169,92.0,0.0,0.0,85.0,90,게임 제작,댄스,267.0,X
5번,정국,부산고등학교,1,178,75.0,80.0,0.0,72.0,85,C++/Python,독서,312.0,X
6번,뷔,국제고등학교,3,179,82.0,85.0,65.0,70.0,78,수학 문제 풀이,독서,380.0,X
7번,제니,국제고등학교,3,163,0.0,100.0,0.0,92.0,94,3D 모델링,댄스,286.0,X

In [ ]:
#🎈리스트 컴프리헨션 활용 방법
#df['결과'] = ['합격' if x >= 400 else 'X' for x in df['총점']]


# for i in df.index:
#     if df.at[i, '총점'] >= 400:
#         df.at[i, '결과'] = '합격'
#     else:
#         df.at[i, '결과'] = 'X'
df

### Column 삭제

In [ ]:
#Column 삭제
#df.drop(columns=[])
df.drop(columns=['동아리','총점'])
#df.drop(columns=['동아리','총점'],inplace=True)

     이름   학교  학년    키     국어     영어     수학     과학   사회    특기  결과
번호
1번  장원영  청담고   1  173   90.0  100.0   85.0   88.0   92  영상편집  합격
3번  차은우  수리고   2  183  100.0   95.0  100.0   98.0   96    보컬  합격
8번  박정민  우리고   3  180  100.0  100.0  100.0  100.0  100    AI  합격

In [ ]:
#Row 삭제 - 인덱스로 삭제하기
df.drop(index='1번')
#df.drop(index='1번',inplace=True)

     이름   학교  학년    키   국어   영어   수학  과학  사회        SW특기 동아리   총점  결과
번호
2번  카리나  팔달고   2  168   85   90   92  84  88        Java  실험  439  합격
3번  차은우  수리고   2  183  100   95  100  98  96      Python  실험  489  합격
4번   민지  부산고   3  169   88   92   78  85  90  JavaScript  댄스  433  합격
5번   정국  부산고   1  178   75   80   70  72  85         C++  독서  382   X
6번    뷔  청담고   3  179   82   85   65  70  78         NaN  독서  380   X
7번   제니  청담고   3  163   95  100   88  92  94         NaN  댄스  469  합격

In [ ]:
#Row 삭제 - 특정 조건의 행만 지우기
#조건에 해당하는 인덱스 번호를 구한다음, 인덱스 번호롤 삭제하기
df[df['총점'] < 400]
df[df['총점'] < 400].index

Index(['2번', '4번', '5번', '6번', '7번'], dtype='object', name='번호')

In [ ]:
df.drop(index=df[df['총점'] < 400].index)
#df.drop(index=df[df['총점'] < 400].index,inplace=True)
df

     이름   학교  학년    키     국어     영어     수학    과학  사회    특기 동아리     총점  결과
번호
1번  장원영  청담고   1  173   90.0  100.0   85.0  88.0  92  영상편집  댄스  455.0  합격
3번  차은우  수리고   2  183  100.0   95.0  100.0  98.0  96    보컬  실험  489.0  합격

In [ ]:
#🎈삭제할 기준이 Column인지 Row인지를  Axis옵션로 나타내는 방법
#df.drop('동아리',axis=1, inplace=True)  #axis=1 열(Column)을 가로질러 옆으로 이동하며 연산 수행
#df.drop(['동아리','총점'],axis=1)
#df.drop(['1번','2번'],axis=0)
df

### Row 추가

In [ ]:
#Row 추가(컬럼수와 동일해야함, Row 전체 수정기능도 됨)  .loc[]
df.loc['8번'] = ['박정민','우리고',3,180,100,100,100,100,100,'AI','노래',500.0,'합격']
df

     이름   학교  학년    키     국어     영어     수학     과학   사회    특기 동아리     총점  결과
번호
1번  장원영  청담고   1  173   90.0  100.0   85.0   88.0   92  영상편집  댄스  455.0  합격
3번  차은우  수리고   2  183  100.0   95.0  100.0   98.0   96    보컬  실험  489.0  합격
8번  박정민  우리고   3  180  100.0  100.0  100.0  100.0  100    AI  노래  500.0  합격

In [ ]:
#Row 추가  .loc[]
import numpy as np
df.loc['8번'] = ['박정민','우리고',3,180,100,100,100,100,100,'AI',np.nan,np.nan,'합격']
df

     이름   학교  학년      키   국어   영어   수학   과학   사회        SW특기  동아리     총점  결과
번호
1번  장원영  청담고   1  173cm   90  100   85   88   92      Python   댄스  455.0  합격
2번  카리나  팔달고   2  168cm   85   90   92   84   88        Java   실험  439.0  합격
3번  차은우  수리고   2  183cm  100   95  100   98   96      Python   실험  489.0  합격
4번   민지  부산고   3  169cm   88   92   78   85   90  JavaScript   댄스  433.0  합격
5번   정국  부산고   1  178cm   75   80   70   72   85         C++   독서  382.0   X
6번    뷔  청담고   3  179cm   82   85   65   70   78         NaN   독서  380.0   X
7번   제니  청담고   3  163cm   95  100   88   92   94         NaN   댄스  469.0  합격
8번  박정민  우리고   3    180  100  100  100  100  100          AI  NaN    NaN  합격

### 셀(Cell) 수정

In [ ]:
#셀(Cell) 수정하기
#1번 학생이 동아리를 변경한 경우
df.loc['1번','동아리'] = '독서'
df

     이름   학교  학년    키     국어     영어     수학     과학   사회    특기 동아리     총점  결과
번호
1번  장원영  청담고   1  173   90.0  100.0   85.0   88.0   92  영상편집  독서  455.0  합격
3번  차은우  수리고   2  183  100.0   95.0  100.0   98.0   96    보컬  실험  489.0  합격
8번  박정민  우리고   3  180  100.0  100.0  100.0  100.0  100    AI  노래  500.0  합격

In [ ]:
#1번학생의 국어 성적과 수학 성적을 수정해야 하는 경우
df.loc['1번',['국어','수학']] = [99,98]
df

     이름   학교  학년    키     국어     영어     수학     과학   사회    특기 동아리     총점  결과
번호
1번  장원영  청담고   1  173   99.0  100.0   98.0   88.0   92  영상편집  독서  455.0  합격
3번  차은우  수리고   2  183  100.0   95.0  100.0   98.0   96    보컬  실험  489.0  합격
8번  박정민  우리고   3  180  100.0  100.0  100.0  100.0  100    AI  노래  500.0  합격

### Column 순서/이름변경

In [ ]:
#Column 순서 변경하기
# 맨 마지막 컬럼을 맨 앞으로 위치 순서로 변경해야 할 경우.
df.columns                           # Column 명 파악하기
c_order = list(df.columns)           # list로 변경하기
c_order

['이름', '학교', '학년', '키', '국어', '영어', '수학', '과학', '사회', '특기', '동아리', '총점', '결과']

In [ ]:
[c_order[-1]] + c_order[0:-1]   # 변경된 순서로 이루어진 리스트
df[[c_order[-1]] + c_order[0:-1]]

    결과   이름   학교  학년    키     국어     영어     수학     과학   사회    특기 동아리     총점
번호
1번  합격  장원영  청담고   1  173   99.0  100.0   98.0   88.0   92  영상편집  독서  455.0
3번  합격  차은우  수리고   2  183  100.0   95.0  100.0   98.0   96    보컬  실험  489.0
8번  합격  박정민  우리고   3  180  100.0  100.0  100.0  100.0  100    AI  노래  500.0

In [ ]:
# Column 이름 변경하기
df.columns
df.columns = ['성명*', '학교', '학년', '신장*', '국어', '영어', '수학', '과학', '사회', '특기*', '동아리',
       '총점', '결과']
df

    성명*   학교  학년    신장*   국어   영어   수학   과학   사회         특기*  동아리     총점  결과
번호
1번  장원영  청담고   1  173cm   90  100   85   88   92      Python   독서  455.0  합격
2번  카리나  팔달고   2  168cm   85   90   92   84   88        Java   실험  439.0  합격
3번  차은우  수리고   2  183cm  100   95  100   98   96      Python   실험  489.0  합격
4번   민지  부산고   3  169cm   88   92   78   85   90  JavaScript   댄스  433.0  합격
5번   정국  부산고   1  178cm   75   80   70   72   85         C++   독서  382.0   X
6번    뷔  청담고   3  179cm   82   85   65   70   78         NaN   독서  380.0   X
7번   제니  청담고   3  163cm   95  100   88   92   94         NaN   댄스  469.0  합격
8번  박정민  우리고   3    180  100  100  100  100  100          AI  NaN    NaN  합격

In [ ]:
df.columns = ['성명', '학교', '학년', '키', '국어', '영어', '수학', '과학', '사회', '특기', '동아리',
       '총점', '결과']
df

,성명,학교,학년,키,국어,영어,수학,과학,사회,특기,동아리,총점,결과
번호,,,,,,,,,,,,,
1번,장원영,청담고,1,173cmcmcm,90,100,85,88,92,Python,독서,455.0,합격
2번,카리나,팔달고,2,168cmcmcm,85,90,92,84,88,Java,실험,439.0,합격
3번,차은우,수리고,2,183cmcmcm,100,95,100,98,96,Python,실험,489.0,합격
4번,민지,부산고,3,169cmcmcm,88,92,78,85,90,JavaScript,댄스,433.0,합격
5번,정국,부산고,1,178cmcmcm,75,80,70,72,85,C++,독서,382.0,X
6번,뷔,청담고,3,179cmcmcm,82,85,65,70,78,NaN,독서,380.0,X
7번,제니,청담고,3,163cmcmcm,95,100,88,92,94,NaN,댄스,469.0,합격
8번,박정민,우리고,3,180cmcm,100,100,100,100,100,AI,NaN,NaN,합격

### 함수활용 Column 수정

In [ ]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/sseegg300/data/refs/heads/main/k-scores.csv')
df['번호']=['1번','2번','3번','4번','5번','6번','7번']
df.set_index('번호', inplace=True)

# url = 'https://raw.githubusercontent.com/sseegg300/data/refs/heads/main/k-scores.csv'
# df = pd.read_csv(url).assign(번호=['1번','2번','3번','4번','5번','6번','7번']).set_index('번호')
df

     이름   학교  학년    키     국어     영어     수학    과학  사회          특기 동아리
번호
1번  장원영  청담고   1  173   90.0  100.0   85.0  88.0  92        영상편집  댄스
2번  카리나  팔달고   2  168   85.0   90.0   92.0   NaN  88     이모티콘 제작  실험
3번  차은우  수리고   2  183  100.0   95.0  100.0  98.0  96          보컬  실험
4번   민지  부산고   3  169   92.0    NaN    NaN  85.0  90       게임 제작  댄스
5번   정국  부산고   1  178   75.0   80.0    NaN  72.0  85  C++/Python  독서
6번    뷔  청담고   3  179   82.0   85.0   65.0  70.0  78    수학 문제 풀이  독서
7번   제니  청담고   3  163    NaN  100.0    NaN  92.0  94      3D 모델링  댄스

In [ ]:
#키 컬러에 cm 붙이기 - 형변환 함수 사용
df['키'] = df['키'].astype(str) + 'cm'

df['국어'] = df['국어'].astype(float)
df

     이름   학교  학년      키     국어     영어     수학    과학  사회          특기 동아리
번호
1번  장원영  청담고   1  173cm   90.0  100.0   85.0  88.0  92        영상편집  댄스
2번  카리나  팔달고   2  168cm   85.0   90.0   92.0   NaN  88     이모티콘 제작  실험
3번  차은우  수리고   2  183cm  100.0   95.0  100.0  98.0  96          보컬  실험
4번   민지  부산고   3  169cm   92.0    NaN    NaN  85.0  90       게임 제작  댄스
5번   정국  부산고   1  178cm   75.0   80.0    NaN  72.0  85  C++/Python  독서
6번    뷔  청담고   3  179cm   82.0   85.0   65.0  70.0  78    수학 문제 풀이  독서
7번   제니  청담고   3  163cm    NaN  100.0    NaN  92.0  94      3D 모델링  댄스

In [ ]:
#🎈키 컬러에 cm 붙이기 - 제작 함수 사용 - apply()
def add_cm(h):
  return str(h)+'cm'

df['키'] = df['키'].apply(add_cm)
df

     이름   학교  학년      키   국어   영어   수학  과학  사회        SW특기 동아리
번호
1번  장원영  청담고   1  173cm   90  100   85  88  92      Python  댄스
2번  카리나  팔달고   2  168cm   85   90   92  84  88        Java  실험
3번  차은우  수리고   2  183cm  100   95  100  98  96      Python  실험
4번   민지  부산고   3  169cm   88   92   78  85  90  JavaScript  댄스
5번   정국  부산고   1  178cm   75   80   70  72  85         C++  독서
6번    뷔  청담고   3  179cm   82   85   65  70  78         NaN  독서
7번   제니  청담고   3  163cm   95  100   88  92  94         NaN  댄스

## 8️⃣그룹화

* 동일한 값으로 그룹을 만들어 합계,평균등 통계값을 계산하기 위함.

In [ ]:
import pandas as pd
# df = pd.read_csv('https://raw.githubusercontent.com/sseegg300/data/refs/heads/main/k-scores.csv')
# df['번호']=['1번','2번','3번','4번','5번','6번','7번']
# df.set_index('번호', inplace=True)

url = 'https://raw.githubusercontent.com/sseegg300/data/refs/heads/main/k-scores.csv'
df = pd.read_csv(url).assign(번호=['1번','2번','3번','4번','5번','6번','7번']).set_index('번호')
df

     이름   학교  학년    키     국어     영어     수학    과학  사회          특기 동아리
번호
1번  장원영  청담고   1  173   90.0  100.0   85.0  88.0  92        영상편집  댄스
2번  카리나  팔달고   2  168   85.0   90.0   92.0   NaN  88     이모티콘 제작  실험
3번  차은우  수리고   2  183  100.0   95.0  100.0  98.0  96          보컬  실험
4번   민지  부산고   3  169   92.0    NaN    NaN  85.0  90       게임 제작  댄스
5번   정국  부산고   1  178   75.0   80.0    NaN  72.0  85  C++/Python  독서
6번    뷔  청담고   3  179   82.0   85.0   65.0  70.0  78    수학 문제 풀이  독서
7번   제니  청담고   3  163    NaN  100.0    NaN  92.0  94      3D 모델링  댄스

In [ ]:
# 학년별로 그룹화
df.groupby('학년')

In [ ]:
#1학년 학생만 가져오기
df.groupby('학년').get_group(1)               #df[df['학년']==1]

     이름   학교  학년    키  국어   영어  수학  과학  사회          특기 동아리
번호
1번  장원영  청담고   1  173  90  100  85  88  92        영상편집  댄스
5번   정국  부산고   1  178  75   80  70  72  85  C++/Python  독서

In [ ]:
#학년별로 계산 가능한 컬럼의 평균 값을 확인
df.groupby('학년').mean(numeric_only=True)

#Pandas의 mean()은 기본적으로 숫자 데이터만 계산하려고 하지만,
#명시적으로 설정을 해주지 않으면 문자열을 어떻게 처리할지 몰라 에러

             키    국어    영어    수학         과학         사회
학년
1   175.500000  82.5  90.0  85.0  80.000000  88.500000
2   175.500000  92.5  92.5  96.0  98.000000  92.000000
3   170.333333  87.0  92.5  65.0  82.333333  87.333333

In [ ]:
#그룹별 크기확인
df.groupby('학년').size()
#df.groupby('학년').size()[3]    #3학년의 크기

학년
1    2
2    2
3    3
dtype: int64

In [ ]:
#학년별 국어점수 평균
df.groupby('학년')['국어'].mean()
#df.groupby('학년')['국어'].mean().astype(int)

학년
1    82.5
2    92.5
3    87.0
Name: 국어, dtype: float64

In [ ]:
#학년별 국영수 평균확인
df.groupby('학년')[['국어','수학','영어']].mean().astype(int)  #평균을 정수로
df.groupby('학년')[['국어','수학','영어']].mean().round(1)     #평균을 소수첫째자리까지

      국어    수학    영어
학년
1   82.5  77.5  90.0
2   92.5  96.0  92.5
3   88.3  77.0  92.3

In [ ]:
#학교별 학년별 평균 구하기/국어점수순
df.groupby(['학교','학년']).mean(numeric_only=True)
df.groupby(['학교','학년']).mean(numeric_only=True).sort_values('국어')

            키     국어     영어     수학    과학    사회
학교  학년
부산고 1   178.0   75.0   80.0   70.0  72.0  85.0
팔달고 2   168.0   85.0   90.0   92.0  84.0  88.0
부산고 3   169.0   88.0   92.0   78.0  85.0  90.0
청담고 3   171.0   88.5   92.5   76.5  81.0  86.0
    1   173.0   90.0  100.0   85.0  88.0  92.0
수리고 2   183.0  100.0   95.0  100.0  98.0  96.0

In [ ]:
#학교별 국어평균
df.groupby('학교')['국어'].mean()
df.groupby('학교')['국어'].mean().sort_values(ascending=False)  #역순 정렬

학교
수리고    100.0
청담고     89.0
팔달고     85.0
부산고     81.5
Name: 국어, dtype: float64

In [ ]:
#학교별 동아리 데이터의 갯수 확인(예:부산고는 3개의 동아리가 있음 )
df.groupby('학교')['동아리'].count()
#df.groupby('학교')['동아리'].size()

학교
부산고    2
수리고    1
청담고    3
팔달고    1
Name: 동아리, dtype: int64

In [ ]:
#🎯학교, 학년별 동아리 갯수를 구하기
#df.groupby(['학교','학년'])['동아리'].count()
#🎯학교 국영수 총합을 구하기
#df.groupby('학교')[['국어','수학','영어']].sum()
#🎯학교, 학년별 국영수 총합을 구하기
df.groupby(['학교','학년'])[['국어','수학','영어']].sum()

           국어     수학     영어
학교  학년
부산고 1    75.0    0.0   80.0
    3    92.0    0.0    0.0
수리고 2   100.0  100.0   95.0
청담고 1    90.0   85.0  100.0
    3    82.0   65.0  185.0
팔달고 2    85.0   92.0   90.0

# 🎯연습문제

In [ ]:
#Pandas 연습 문제
import pandas as pd

ott_data = {
    '콘텐츠명': ['오징어 게임 2', '더 글로리', '무빙', '피지컬: 100', '환승연애', '흑백요리사', '카지노'],
    '플랫폼': ['Netflix', 'Netflix', 'Disney+', 'Netflix', 'TVING', 'Netflix', 'Disney+'],
    '개봉년도': [2024, 2022, 2023, 2023, 2021, 2024, 2022],
    '시청시간': [16.5, 6.2, 5.8, 2.1, 1.5, 4.8, 3.2],    #(단위:억)
    '평점': [9.2, 9.5, 9.7, 8.8, 9.1, 9.4, 8.9]
}

df = pd.DataFrame(ott_data)

In [ ]:
df

       콘텐츠명      플랫폼  개봉년도  시청시간   평점
0  오징어 게임 2  Netflix  2024  16.5  9.2
1     더 글로리  Netflix  2022   6.2  9.5
2        무빙  Disney+  2023   5.8  9.7
3  피지컬: 100  Netflix  2023   2.1  8.8
4      환승연애    TVING  2021   1.5  9.1
5     흑백요리사  Netflix  2024   4.8  9.4
6       카지노  Disney+  2022   3.2  8.9

In [ ]:
#✅[문제1] 콘텐츠명만 출력해 보세요
df['콘텐츠명']

0    오징어 게임 2
1       더 글로리
2          무빙
3    피지컬: 100
4        환승연애
5       흑백요리사
6         카지노
Name: 콘텐츠명, dtype: object

In [ ]:
#✅[문제2] 콘텐츠명,플랫폼을 출력해 보세요
df[['콘텐츠명','플랫폼']]

       콘텐츠명      플랫폼
0  오징어 게임 2  Netflix
1     더 글로리  Netflix
2        무빙  Disney+
3  피지컬: 100  Netflix
4      환승연애    TVING
5     흑백요리사  Netflix
6       카지노  Disney+

In [ ]:
#✅[문제3] 개봉년도가 최근인것부터 정렬하시오.(내림차순)
#(심화:개봉년도가 같을 경우는 평점순으로, 평점은 오름차순으로)
df.sort_values(['개봉년도','평점'],ascending=[False,True])

       콘텐츠명      플랫폼  개봉년도  시청시간(억)   평점
0  오징어 게임 2  Netflix  2024     16.5  9.2
5     흑백요리사  Netflix  2024      4.8  9.4
3  피지컬: 100  Netflix  2023      2.1  8.8
2        무빙  Disney+  2023      5.8  9.7
6       카지노  Disney+  2022      3.2  8.9
1     더 글로리  Netflix  2022      6.2  9.5
4      환승연애    TVING  2021      1.5  9.1

In [ ]:
#✅[문제4] 개봉년도가 2023년 이후 인것만 콘텐츠명,개봉년도 출력하기
df.loc[df['개봉년도'] >= 2023,['콘텐츠명','개봉년도']]

       콘텐츠명  개봉년도
0  오징어 게임 2  2024
2        무빙  2023
3  피지컬: 100  2023
5     흑백요리사  2024

In [ ]:
#✅[문제5] 추천점수 Column을 추가 하세요.
# 추천점수 = (시청시간*평점)//10
df['추천점수'] = (df['시청시간']*df['평점'])//10
df

       콘텐츠명      플랫폼  개봉년도  시청시간   평점  추천점수
0  오징어 게임 2  Netflix  2024  16.5  9.2  15.0
1     더 글로리  Netflix  2022   6.2  9.5   5.0
2        무빙  Disney+  2023   5.8  9.7   5.0
3  피지컬: 100  Netflix  2023   2.1  8.8   1.0
4      환승연애    TVING  2021   1.5  9.1   1.0
5     흑백요리사  Netflix  2024   4.8  9.4   4.0
6       카지노  Disney+  2022   3.2  8.9   2.0